export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const LOAD_CHARTS_SUCCESS = "LOAD_CHARTS_SUCCESS";
export const ADD_CHART = "ADD_CHART";
export const CREATE_ALERT = "CREATE_ALERT";
